### PR TITLE
chore: Update goreleaser syntax

### PR DESCRIPTION
**Pull request by jsoref**
* https://goreleaser.com/deprecations#brew

### CODE REVIEW

**Comment by caarlos0** [comment]
hey @jsoref, did you use a bot for this?

if so, I'm interested! can you ping me on twitter? (https://twitter.com/caarlos0)

**Comment by jsoref** [comment]
@caarlos0: No. I should though. It's very bottish.

I am definitely doing copy+paste. I basically have left one tab to the left of my current tab. The process is:

1. Tab 1 [log listing failures](https://travis-ci.org/github/goreleaser/godownloader/builds/689321738)
1. Tab 2 [deprecation notices](https://goreleaser.com/deprecations#archive)
1. Window 2 - Tab 3 - saved commit for copy+paste
1. Window 2 - Tab 4 - work place
---

1. Copy the url from Tab 1 -- actually, just the stuff after the domain
   1. Paste it into Tab 4
   1. Insert `tree/` before `master/`
   1. Enter
1. Edit url
   1. Use my org instead of the main org
   1. Enter
1. Edit the sections as applicable based on Tab 1 / Tab 2
   1. Use GitHub editor's `<tab>` behavior.
1. Open the repository's root in a new tab (5)
   1. Click commits and determine if the repository uses semantic commit naming
   1. Close tab
1. Copy commit message from Tab 3 to Tab 4
1. At the bottom switch to new branch
1. Copy the branch name from Tab 3 to Tab 4
1. Commit
1. If the repo name is too common, rename it
1. Go to parent repository (to avoid accidentally creating a PR into the fork, because GitHub)
1. Copy the deprecation bullet urls from Tab 3 (if lucky) or Tab 2
1. Create PR
1. Switch to Tab 1
1. Find again for `deprecation`

**Comment by caarlos0** [comment]
wow, I was hopping it was something automated :| 

thanks for the PRs anyway 🚀

**Comment by jsoref** [comment]
One could probably use Automator.app to do it...

I don't want to have all of these repositories on my computer, it doesn't serve any particular purpose.

**Pull request merged**
